### ISSUE TITLE
Do not switch to the next code segment after pressing Enter

### ISSUE THREAD

**Issue by ialtone** [webbestmaster/markdown-pro#1]
When I enter two spaces and press Enter again, I find that the original style does not change, for example.

![image](https://user-images.githubusercontent.com/77558124/221363644-4bdecc97-2689-49e1-bdb0-ca565f607eae.png)

**Comment by webbestmaster** [comment]
hi,

try to use config option `useLineBreak: true`

**Comment by ialtone** [comment]
> 你好，
> 
> 尝试使用配置选项`useLineBreak: true`
> 
> 或\和
> 
> 在标题和文本之间添加空间行

Adding  empty line is feasible, but useLineBreak: true does not work.

**Comment by webbestmaster** [comment]
oh, sorry, about `useLineBreak: true` - my mistake, this parameter works different.

yep, just use empty line after a header
